name: first workflow

on:
     push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps :
    - name : print build start
      run : echo "build start" 
 build:
    runs-on: ubuntu-latest
    steps :
    - name : print pwd
      run : echo "pwd"
        
